public class Main {
    public static void main(String[] args) {
        PrimeNumberGenerator newprime = new PrimeNumberGenerator();
        System.out.println( newprime.toString());
        newprime.nextPrime();
        System.out.println( newprime.toString());
        newprime.nextPrime();
        System.out.println( newprime.toString());
        newprime.nextPrime();
        System.out.println( newprime.toString());
        newprime.nextPrime();
        System.out.println( newprime.toString());
        newprime.nextPrime();
        System.out.println( newprime.toString());
        newprime.nextPrime();
        System.out.println( newprime.toString());
        newprime.nextPrime();
        System.out.println( newprime.toString());
        newprime.nextPrime();
        System.out.println( newprime.toString());
        newprime.nextPrime();
        System.out.println( newprime.toString());
        Hashmap hashmap2 = new Hashmap();
       hashmap2.insert(1, 85);
       System.out.println( hashmap2.toString());
       hashmap2.insert(2, 85);
       System.out.println( hashmap2.toString());
       hashmap2.insert(3, 85);
       System.out.println( hashmap2.toString());
       hashmap2.remove(3);
       System.out.println( hashmap2.toString());
       hashmap2.insert(4, 85);
       System.out.println( hashmap2.toString());
       hashmap2.insert(5, 85);
       System.out.println( hashmap2.toString());
       hashmap2.insert(6, 85);
       System.out.println( hashmap2.toString());
       hashmap2.insert(7, 85);
       System.out.println( hashmap2.toString());
       hashmap2.insert(9, 85);
       System.out.println( hashmap2.toString());
       hashmap2.insert(10, 85);
       System.out.println( hashmap2.toString());
       hashmap2.insert(111, 85);
       System.out.println( hashmap2.toString());
       hashmap2.insert(111, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(111, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(112, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(113, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(114, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(115, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(116, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(117, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(118, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(119, 95);
       System.out.println( hashmap2.toString());
       hashmap2.remove(119);
       System.out.println( hashmap2.toString());
       hashmap2.remove(118);
       System.out.println( hashmap2.toString());
       hashmap2.remove(117);
       System.out.println( hashmap2.toString());
       hashmap2.remove(116);
       System.out.println( hashmap2.toString());
       hashmap2.remove(115);
       System.out.println( hashmap2.toString());
       hashmap2.remove(114);
       System.out.println( hashmap2.toString());
       hashmap2.remove(113);
       System.out.println( hashmap2.toString());
        Hashmap hasmap3 = new Hashmap("13[-,u1:85%,u2:85%,u3:85%,u4:85%,u5:85%,u6:85%,u7:85%,-,u9:85%,-,-,-,u10:85%,-,-,-,-,-,-,-,-,-,u111:95%,u112:95%,-,-,-,-,-,-,-]");
        System.out.println( hasmap3.toString());
        System.out.println( hasmap3.toStringOneLine());
        System.out.println( hashmap2.toStringOneLine());
        hashmap2.remove(113);
        System.out.println( hashmap2.toString());
        hashmap2.remove(112);
        System.out.println( hashmap2.toString());
        hashmap2.remove(111);
        System.out.println( hashmap2.toString());
        hashmap2.remove(10);
        System.out.println( hashmap2.toString());
        hashmap2.remove(9);
        System.out.println( hashmap2.toString());
        hashmap2.remove(8);
        System.out.println( hashmap2.toString());
        hashmap2.remove(7);
        hashmap2.remove(6);
        System.out.println( hashmap2.toString());
        hashmap2.remove(5);
        System.out.println( hashmap2.toString());
        hashmap2.remove(4);
        System.out.println( hashmap2.toString());
        hashmap2.remove(3);
        hashmap2.remove(2);
        System.out.println( hashmap2.toString());
        hashmap2.remove(1);
        System.out.println( hashmap2.toString());
        hashmap2.remove(8);
        System.out.println( hashmap2.toString());
        hashmap2.remove(7);
        hashmap2.insert(1, 85);
       System.out.println( hashmap2.toString());
       hashmap2.insert(2, 85);
       System.out.println( hashmap2.toString());
       hashmap2.insert(3, 85);
       System.out.println( hashmap2.toString());
       hashmap2.remove(3);
       System.out.println( hashmap2.toString());
       hashmap2.insert(4, 85);
       System.out.println( hashmap2.toString());
       hashmap2.insert(5, 85);
       System.out.println( hashmap2.toString());
       hashmap2.insert(6, 85);
       System.out.println( hashmap2.toString());
       hashmap2.insert(7, 85);
       System.out.println( hashmap2.toString());
       hashmap2.insert(8, 85);
       System.out.println( hashmap2.toString());
       hashmap2.insert(9, 85);
       System.out.println( hashmap2.toString());
       hashmap2.insert(10, 85);
       System.out.println( hashmap2.toString());
       hashmap2.insert(111, 85);
       System.out.println( hashmap2.toString());
       hashmap2.insert(111, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(111, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(112, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(113, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(114, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(115, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(116, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(117, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(118, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(119, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(300020, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(300021, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(300022, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(300023, 95);
       System.out.println( hashmap2.toString());
       hashmap2.insert(300024, 95);
       System.out.println( hashmap2.toString());
       Hashmap hasmap4 = new Hashmap("19[u300020:95%,u1:85%,u2:85%,-,u4:85%,u5:85%,u6:85%,u7:85%,u8:85%,u9:85%,u113:95%,u300021:95%,u300022:95%,u300023:95%,u300024:95%,-,-,u111:95%,u112:95%,u10:85%,u114:95%,u115:95%,u116:95%,u117:95%,u118:95%,u119:95%,-,-]");
       System.out.println( hasmap4.toString());
    }
    
}
