public class Main {
    // Output is in output.txt
    public static void main(String[] args) {
        LinkedList LL1 = new LinkedList();

        System.out.println(LL1.toString());
        System.out.println(LL1.contains(3, 4));
        System.out.println(LL1.length());
        LinkedList LL2 = new LinkedList(3,5);
        LL1.appendList(LL2);
        LL1.append(1000000, 20);
        LL1.append(3,4);
        LL2.append(3,4);
        LL2.append(4, 5);
        LL1.appendList(LL2);
        System.out.println(LL1.toString());
        System.out.println(LL2.toString());
        System.out.println(LL1.contains(4,2));
        System.out.println(LL1.contains(3, 4));
        System.out.println(LL2.contains(4, 5));
        System.out.println(LL1.length());
        System.out.println(LL2.length());
        LL1.appendList(LL2);
        System.out.println(LL1.toString());
        LinkedList LL3 = LL1.reversed();
        System.out.println(LL3.toString());




        LinkedList LL4 = new LinkedList();
        LL4.append(3, 3);
        LL4.append(2, 3);
        LL4.append(1, 3);
        LL4.append(0, 3);
        LL4.append(0, 2);
        LL4.append(0, 1);
        LL4.append(0, 0);
        LL4.append(1, 0);

        LinkedList LL5 = new LinkedList();
        LL5.append(3, 3);
        LL5.append(3, 2);
        LL5.append(3, 1);
        LL5.append(3, 0);
        LL5.append(2, 0);
        LL5.append(1, 0);

        LinkedList LL6 = new LinkedList();
        LL6.append(3, 3);
        LL6.append(1, 2);
        LL6.append(3, 1);
        LL6.append(3, 0);
        LL6.append(2, 0);
        LL6.append(1, 0);

        LinkedList LL7 = new LinkedList();
        LL7.append(3, 3);
        LL7.append(4, 3);
        LL7.append(3, 1);
        LL7.append(3, 2);
        LL7.append(2, 0);
        LL7.append(1, 0);

        LinkedList LL8 = new LinkedList();

        Maze m = new Maze("input.txt");

        Maze m2 = new Maze(m);

        System.out.println(m.toString());
        System.out.println(m2.toString());
        System.out.println(m.validSolution(3, 3, 1, 0,LL4));
        System.out.println(m.validSolution(3, 3, 1, 0,LL5));
        System.out.println(m.validSolution(3, 3, 1, 0,LL6));
        System.out.println(m.validSolution(3, 3, 1, 0,LL7));
        System.out.println(m.validSolution(2, 3, 1, 0,LL6));
        System.out.println(m.validSolution(3, 4, 1, 0,LL6));
        System.out.println(m.validSolution(3, 3, 0, 1,LL6));

        System.out.println(m.validSolution(-3, 3, 1, 0,LL6));
        System.out.println(m.validSolution(3, -3, 1, 0,LL6));
        System.out.println(m.validSolution(3, 3, -1, 0,LL6));
        System.out.println(m.validSolution(3, 3, 1, -3,LL6));

        System.out.println(m.validSolution(13, 3, 1, 0,LL6));
        System.out.println(m.validSolution(3, 13, 1, 0,LL6));
        System.out.println(m.validSolution(3, 3, 11, 0,LL6));
        System.out.println(m.validSolution(3, 3, 1, 10,LL6));

        
        System.out.println(m.validSolution(3, 3, 1, 0,LL8));

        System.out.println(m.solve(0,0,0,0));
        System.out.println(m.solve(1,3,4,4));
        System.out.println(m.solve(-1,3,4,4));
        System.out.println(m.solve(1,-3,4,4));
        System.out.println(m.solve(1,3,-4,4));
        System.out.println(m.solve(1,3,4,-4));
        System.out.println(m.solve(10,3,4,4));
        System.out.println(m.solve(1,30,4,4));
        System.out.println(m.solve(1,3,40,4));
        System.out.println(m.solve(1,3,4,40));
        LinkedList list = new LinkedList();
        list.append(2, 36);
        list.append(1, 36);
        list.append(0, 36);
        list.append(0, 35);
        list.append(0, 34);
        list.append(0, 33);
        list.append(0, 32);
        list.append(0, 31);
        list.append(0, 30);
        list.append(0, 29);
        list.append(0, 28);
        list.append(0, 27);
        list.append(0, 26);
        list.append(0, 25);
        list.append(0, 24);
        list.append(0, 23);
        list.append(0, 22);
        list.append(0, 21);
        list.append(0, 20);
        list.append(0, 19);
        list.append(0, 18);
        list.append(0, 17);
        list.append(0, 16);
        list.append(0, 15);
        list.append(0, 14);
        list.append(0, 13);
        list.append(0, 12);
        list.append(0, 11);
        list.append(0, 10);
        list.append(0, 9);
        list.append(0, 8);
        list.append(0, 7);
        list.append(0, 6);
        list.append(0, 5);
        list.append(0, 4);
        list.append(0, 3);
        list.append(0, 2);
        list.append(0, 1);
        list.append(0, 0);
        list.append(1, 0);
        list.append(1, 1);
        list.append(1, 2);
        list.append(1, 3);
        list.append(1, 4);
        list.append(1, 5);
        list.append(1, 6);
        list.append(1, 7);
        list.append(1, 8);
        list.append(1, 9);
        list.append(1, 10);
        list.append(1, 11);
        list.append(1, 12);
        list.append(1, 13);
        list.append(1, 14);
        list.append(1, 15);
        list.append(1, 16);
        list.append(1, 17);
        list.append(1, 18);
        list.append(1, 19);
        list.append(1, 20);
        list.append(1, 21);
        list.append(1, 22);
        list.append(1, 23);
        list.append(1, 24);
        list.append(1, 25);
        list.append(1, 26);
        list.append(1, 27);
        list.append(1, 28);
        list.append(1, 29);
        list.append(1, 30);
        list.append(1, 31);
        list.append(1, 32);
        list.append(1, 33);
        list.append(1, 34);
        list.append(1, 35);
        list.append(2, 35);
        list.append(2, 34);
        list.append(2, 33);
        list.append(2, 32);
        list.append(2, 31);
        list.append(2, 30);
        list.append(2, 29);
        list.append(2, 28);
        list.append(2, 27);
        list.append(2, 26);
        list.append(2, 25);
        list.append(2, 24);
        list.append(2, 23);
        list.append(2, 22);
        list.append(2, 21);
        list.append(2, 20);
        list.append(2, 19);
        list.append(2, 18);
        list.append(2, 17);
        list.append(2, 16);
        list.append(2, 15);
        list.append(2, 14);
        list.append(2, 13);
        list.append(2, 12);
        list.append(2, 11);
        list.append(2, 10);
        list.append(2, 9);
        list.append(2, 8);
        list.append(2, 7);
        list.append(2, 6);
        list.append(2, 5);
        list.append(2, 4);
        list.append(2, 3);
        list.append(2, 2);
        list.append(2, 1);
        list.append(2, 0);
        list.append(3, 0);
        list.append(3, 1);
        list.append(3, 2);
        list.append(3, 3);
        list.append(3, 4);
        list.append(3, 5);
        list.append(3, 6);
        list.append(3, 7);
        list.append(3, 8);
        list.append(3, 9);
        list.append(3, 10);
        list.append(3, 11);
        list.append(3, 12);
        list.append(3, 13);
        list.append(3, 14);
        list.append(3, 15);
        list.append(3, 16);
        list.append(3, 17);
        list.append(3, 18);
        list.append(3, 19);
        list.append(3, 20);
        list.append(3, 21);
        list.append(3, 22);
        list.append(3, 23);
        list.append(3, 24);
        list.append(3, 25);
        list.append(3, 26);
        list.append(3, 27);
        list.append(3, 28);
        list.append(3, 29);
        list.append(3, 30);
        list.append(3, 31);
        list.append(3, 32);
        list.append(3, 33);
        list.append(3, 34);
        list.append(3, 35);
        list.append(3, 36);
        list.append(3, 37);
        list.append(2, 37);
        list.append(1, 37);
        list.append(0, 37);
        list.append(0, 38);
        list.append(0, 39);
        list.append(0, 40);
        list.append(0, 41);
        list.append(0, 42);
        list.append(0, 43);
        list.append(0, 44);
        list.append(0, 45);
        list.append(0, 46);
        list.append(0, 47);
        list.append(0, 48);
        list.append(0, 49);
        list.append(0, 50);
        list.append(0, 51);
        list.append(0, 52);
        list.append(0, 53);
        list.append(0, 54);
        list.append(0, 55);
        list.append(0, 56);
        list.append(0, 57);
        list.append(0, 58);
        list.append(0, 59);
        list.append(0, 60);
        list.append(0, 61);
        list.append(0, 62);
        list.append(0, 63);
        list.append(0, 64);
        list.append(0, 65);
        list.append(0, 66);
        list.append(0, 67);
        list.append(0, 68);
        list.append(0, 69);
        list.append(0, 70);
        list.append(0, 71);
        list.append(0, 72);
        list.append(0, 73);
        list.append(0, 74);
        list.append(0, 75);
        list.append(0, 76);
        list.append(0, 77);
        list.append(0, 78);
        list.append(0, 79);
        list.append(0, 80);
        list.append(0, 81);
        list.append(0, 82);
        list.append(0, 83);
        list.append(0, 84);
        list.append(0, 85);
        list.append(0, 86);
        list.append(0, 87);
        list.append(0, 88);
        list.append(0, 89);
        list.append(0, 90);
        list.append(0, 91);
        list.append(0, 92);
        list.append(0, 93);
        list.append(0, 94);
        list.append(0, 95);
        list.append(0, 96);
        list.append(0, 97);
        list.append(0, 98);
        list.append(0, 99);
        list.append(1, 99);
        list.append(1, 98);
        list.append(1, 97);
        list.append(1, 96);
        list.append(1, 95);
        list.append(1, 94);
        list.append(1, 93);
        list.append(1, 92);
        list.append(1, 91);
        list.append(1, 90);
        list.append(1, 89);
        list.append(1, 88);
        list.append(1, 87);
        list.append(1, 86);
        list.append(1, 85);
        list.append(1, 84);
        list.append(1, 83);
        list.append(1, 82);
        list.append(1, 81);
        list.append(1, 80);
        list.append(1, 79);
        list.append(1, 78);
        list.append(1, 77);
        list.append(1, 76);
        list.append(1, 75);
        list.append(1, 74);
        list.append(1, 73);
        list.append(1, 72);
        list.append(1, 71);
        list.append(1, 70);
        list.append(1, 69);
        list.append(1, 68);
        list.append(1, 67);
        list.append(1, 66);
        list.append(1, 65);
        list.append(1, 64);
        list.append(1, 63);
        list.append(1, 62);
        list.append(1, 61);
        list.append(1, 60);
        list.append(1, 59);
        list.append(1, 58);
        list.append(1, 57);
        list.append(1, 56);
        list.append(1, 55);
        list.append(1, 54);
        list.append(1, 53);
        list.append(1, 52);
        list.append(1, 51);
        list.append(1, 50);
        list.append(1, 49);
        list.append(1, 48);
        list.append(1, 47);
        list.append(1, 46);
        list.append(1, 45);
        list.append(1, 44);
        list.append(1, 43);
        list.append(1, 42);
        list.append(1, 41);
        list.append(1, 40);
        list.append(1, 39);
        list.append(1, 38);
        list.append(2, 38);
        list.append(2, 39);
        list.append(2, 40);
        list.append(2, 41);
        list.append(2, 42);
        list.append(2, 43);
        list.append(2, 44);
        list.append(2, 45);
        list.append(2, 46);
        list.append(2, 47);
        list.append(2, 48);
        list.append(2, 49);
        list.append(2, 50);
        list.append(2, 51);
        list.append(2, 52);
        list.append(2, 53);
        list.append(2, 54);
        list.append(2, 55);
        list.append(2, 56);
        list.append(2, 57);
        list.append(2, 58);
        list.append(2, 59);
        list.append(2, 60);
        list.append(2, 61);
        list.append(2, 62);
        list.append(2, 63);
        list.append(2, 64);
        list.append(2, 65);
        list.append(2, 66);
        list.append(2, 67);
        list.append(2, 68);
        list.append(2, 69);
        list.append(2, 70);
        list.append(2, 71);
        list.append(2, 72);
        list.append(2, 73);
        list.append(2, 74);
        list.append(2, 75);
        list.append(2, 76);
        list.append(2, 77);
        list.append(2, 78);
        list.append(2, 79);
        list.append(2, 80);
        list.append(2, 81);
        list.append(2, 82);
        list.append(2, 83);
        list.append(2, 84);
        list.append(2, 85);
        list.append(2, 86);
        list.append(2, 87);
        list.append(2, 88);
        list.append(2, 89);
        list.append(2, 90);
        list.append(2, 91);
        list.append(2, 92);
        list.append(2, 93);
        list.append(2, 94);
        list.append(2, 95);
        list.append(2, 96);
        list.append(2, 97);
        list.append(2, 98);
        list.append(2, 99);
        list.append(3, 99);
        list.append(3, 98);
        list.append(3, 97);
        list.append(3, 96);
        list.append(3, 95);
        list.append(3, 94);
        list.append(3, 93);
        list.append(3, 92);
        list.append(3, 91);
        list.append(3, 90);
        list.append(3, 89);
        list.append(3, 88);
        list.append(3, 87);
        list.append(3, 86);
        list.append(3, 85);
        list.append(3, 84);
        list.append(3, 83);
        list.append(3, 82);
        list.append(3, 81);
        list.append(3, 80);
        list.append(3, 79);
        list.append(3, 78);
        list.append(3, 77);
        list.append(3, 76);
        list.append(3, 75);
        list.append(3, 74);
        list.append(3, 73);
        list.append(3, 72);
        list.append(3, 71);
        list.append(3, 70);
        list.append(3, 69);
        list.append(3, 68);
        list.append(3, 67);
        list.append(3, 66);
        list.append(3, 65);
        list.append(3, 64);
        list.append(3, 63);
        list.append(3, 62);
        list.append(3, 61);
        list.append(3, 60);
        list.append(3, 59);
        list.append(3, 58);
        list.append(3, 57);
        list.append(3, 56);
        list.append(3, 55);
        list.append(3, 54);
        list.append(3, 53);
        list.append(3, 52);
        list.append(3, 51);
        list.append(3, 50);
        list.append(3, 49);
        list.append(3, 48);
        list.append(3, 47);
        list.append(3, 46);
        list.append(3, 45);
        list.append(3, 44);
        list.append(3, 43);
        list.append(3, 42);
        list.append(3, 41);
        list.append(3, 40);
        list.append(3, 39);
        list.append(3, 38);
        list.append(4, 38);
        list.append(4, 39);
        list.append(4, 40);
        list.append(4, 41);
        list.append(4, 42);
        list.append(4, 43);
        list.append(4, 44);
        list.append(4, 45);
        list.append(4, 46);
        list.append(4, 47);
        list.append(4, 48);
        list.append(4, 49);
        list.append(4, 50);
        list.append(4, 51);
        list.append(4, 52);
        list.append(4, 53);
        list.append(4, 54);
        list.append(4, 55);
        list.append(4, 56);
        list.append(4, 57);
        list.append(4, 58);
        list.append(4, 59);
        list.append(4, 60);
        list.append(4, 61);
        list.append(4, 62);
        list.append(4, 63);
        list.append(4, 64);
        list.append(4, 65);
        list.append(4, 66);
        list.append(4, 67);
        list.append(4, 68);
        list.append(4, 69);
        list.append(4, 70);
        list.append(4, 71);
        list.append(4, 72);
        list.append(4, 73);
        list.append(4, 74);
        list.append(4, 75);
        list.append(4, 76);
        list.append(4, 77);
        list.append(4, 78);
        list.append(4, 79);
        list.append(4, 80);
        list.append(4, 81);
        list.append(4, 82);
        list.append(4, 83);
        list.append(4, 84);
        list.append(4, 85);
        list.append(4, 86);
        list.append(4, 87);
        list.append(4, 88);
        list.append(4, 89);
        list.append(4, 90);
        list.append(4, 91);
        list.append(4, 92);
        list.append(4, 93);
        list.append(4, 94);
        list.append(4, 95);
        list.append(4, 96);
        list.append(4, 97);
        list.append(4, 98);
        list.append(4, 99);
        System.out.println(m.validSolution(2,36,4,99,list));
        System.out.println(m.validStarts(0, 0));
    }
}